# -*- coding: utf-8 -*-
"""Despliegue_trabajo_final_red_neuronal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0LxwpxVBUixS49P2wuy0nCeMGYAk9k0

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Importamos librerías básicas
#Ayudas
import pandas as pd               # manipulacion dataframes
import numpy as np                # matrices y vectores
import matplotlib.pyplot as plt   # gráfica

#Cargamos el modelo
import pickle
filename = 'modelo-class-RNN.pkl'
modelNN,labelencoder,variables, min_max_scaler= pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
data = pd.read_csv("Hipertension_Arterial_Mexico_futuros.csv")
data.head()

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st
st.title('Predicción de riesgo de hipertensión Arterial')
edad= st.slider('Edad', min_value=9, max_value=90, value=30, step=1)
concentracion_hemoglobina= st.slider('concentracion_hemoglobina', min_value=8, max_value=18, value=100, step=1)
valor_colesterol_ldl = st.slider('valor_colesterol_ldl', min_value=20, max_value=90, value=80, step=1)
resultado_glucosa = st.slider('resultado_glucosa', min_value=50, max_value=250, value=100, step=1)
valor_insulina = st.slider('valor_insulina', min_value=2.0, max_value=25.0, value=15.0, step=0.5)
valor_trigliceridos = st.slider('valor_trigliceridos', min_value=30, max_value=400, value=150, step=1)
valor_folato = st.slider('valor_folato', min_value=4.0, max_value=25.0, value=10.0, step=0.1)
valor_homocisteina = st.slider('valor_homocisteina', min_value=5.0, max_value=30.0, value=12.0, step=0.1)
valor_vitamina_bdoce = st.slider('valor_vitamina_bdoce', min_value=200, max_value=900, value=400, step=1)
valor_vitamina_d = st.slider('valor_vitamina_d', min_value=10, max_value=100, value=50, step=1)
estatura = st.slider('estatura', min_value=70.0, max_value=210.0, value=160.0, step=0.5)
distancia_rodilla_talon = st.slider('distancia_rodilla_talon', min_value=30.0, max_value=70.0, value=45.0, step=0.5)
circunferencia_de_la_pantorrilla = st.slider('circunferencia_de_la_pantorrilla', min_value=20.0, max_value=60.0, value=34.0, step=0.5)
tension_arterial = st.slider('tension_arterial', min_value=80, max_value=200, value=120, step=1)
actividad_total = st.slider('actividad_total', min_value=0, max_value=7000, value=1500, step=10)

# Armar el DataFrame con los mismos nombres de variables
datos = [[
    edad, concentracion_hemoglobina, valor_colesterol_ldl, resultado_glucosa,
    valor_insulina, valor_trigliceridos, valor_folato, valor_homocisteina,
    valor_vitamina_bdoce, valor_vitamina_d, estatura, distancia_rodilla_talon,
    circunferencia_de_la_pantorrilla, tension_arterial, actividad_total]]


#Dataframe con los mismos nombres de variables
data = pd.DataFrame(datos, columns=[
    'edad','concentracion_hemoglobina','valor_colesterol_ldl','resultado_glucosa',
    'valor_insulina','valor_trigliceridos','valor_folato','valor_homocisteina',
    'valor_vitamina_bdoce','valor_vitamina_d','estatura','distancia_rodilla_talon',
    'circunferencia_de_la_pantorrilla','tension_arterial','actividad_total'])

#Se realiza la preparación debe ser igual al aprendizaje
data_preparada=data.copy()

#Normalización de variables numericas
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
variables_a_normalizar = data_preparada.select_dtypes(include=['float64', 'int64']).columns  # variables numéricas
min_max_scaler.fit(data[variables_a_normalizar])  # Ajuste de parámetro
data_preparada[variables_a_normalizar] = min_max_scaler.transform(data[variables_a_normalizar])
data_preparada.head()

#Hacemos la predicción con el modelo
Y_fut = modelNN.predict(data_preparada)
print(Y_fut)
data['Predicción']=labelencoder.inverse_transform(Y_fut)
data.head()

"""# **Predicciones**
La calidad del modelo es:

- Exactirtud: 0.83
- Precisión: 0.83
- Recall: 0.82
- Area ROC: 0.89
"""

data